name: Regen3000
main: fr.richie.Regen3000.RMPlugin
author: richie3366
version: 1.4.5.0
commands:
  regen3000:
    description: Regen3000 main command.
    usage: /<command>
    aliases: [/rm,regenmine,r3000]